### ISSUE TITLE
Add owners endpoint

### ISSUE THREAD

**Issue by Rebenar** [dashofcode/tracker_api#50] opened 2015-07-01 10:16 UTC
Need to add:
1. Owners endpoint for story(/projects/{project_id}/stories/{story_id}/owners) https://www.pivotaltracker.com/help/api/rest/v5#projects_project_id_stories_story_id_owners_get 
2. Add method to story resource to parse owners for story.
3. Tests.

**Comment by forest** [comment] 2015-07-01 17:07
You can get the owners now using the `fields` param and eager loading.

```
client.project.stories(fields: ':default,owners')
project.story(story_id, fields: ':default,owners')
```

We can also add a method on story to get the owners lazily if they were not already retrieved similar to comments and tasks.
https://github.com/dashofcode/tracker_api/blob/master/lib/tracker_api/resources/story.rb#L72-72

**Comment by Rebenar** [comment] 2015-07-02 13:53
Yea, I want to do similar to 
https://github.com/dashofcode/tracker_api/blob/master/lib/tracker_api/resources/story.rb#L72-72

Can you test this? This isn't work for me. Response has empty owners. vvv
```
client.project.stories(fields: ':default,owners')
project.story(story_id, fields: ':default,owners')
```
Example:
```
[8] pry(#<JiraToPivotal::Pivotal::Project>)> @project.story(95351028, {fields: ':default,owners'} ).owner_ids
=> [1509820]
[9] pry(#<JiraToPivotal::Pivotal::Project>)> @project.story(95351028, {fields: ':default,owners'} ).owners
=> []
```

**Comment by forest** [comment] 2015-07-02 17:57
I confirmed the behavior. I think this is a bug in Pivotal Tracker's API
and sent them an email regarding this.

You can get the owned_by person object, but you will just get the first
owner this way and not all the owners.

project.story(story_id, fields: ':default,owned_by')

**Comment by forest** [comment] 2015-07-04 06:02
I got confirmation that this is a Pivotal Tracker API bug. Here is their response with a temporary workaround.

------
Thanks for contacting us and taking the time to let us know about this issue. I'm sorry you discovered it before we did.

Thanks so much for including the example showing the exact issue.

I've created a story to address this issue and we will update you when a fix has been deployed.

Meanwhile, you can work around the problem by leaving out :default. For example, 
curl -X GET -H "X-TrackerToken: $TOKEN" "https://www.pivotaltracker.com/services/v5/projects/${PROJECT_ID}/stories/${STORY_ID}?fields=owners"
will return the hydrated owners.

It's inconvenient since you'll have to type out all the fields you want in the fields=, but at least you can get the information back.
------

I'll report back here when they deploy a fix.

**Comment by Rebenar** [comment] 2015-07-08 09:17
Ok, thanks.

**Closed** 2015-07-14 19:07 UTC
Labels: enhancement

**Comment by forest** [comment] 2015-07-14 19:09
Eager loading is still broken for story.owners until Pivotal addresses the issue, but lazing loading was added in #52. This should keep you going.
